import Head from 'next/head'

import Layout from '../components/layout';

import GithubSignIn from "../components/GithubSignIn";
import { GithubContext } from '../components/Github/GithubContext';

export default function Home() {

  return (
    <>
      <Head>
        <title>Code Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Layout>
            <h1>Code Review</h1>
            <GithubContext>
                <GithubSignIn />
            </GithubContext>
        </Layout>
    </>
  )
}
