import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { octokit } from '../lib/octokit';
import { useEffect, useState } from 'react';

// styles
import { styled } from '@mui/system';
import { Container } from "@mui/material";
import GithubSignIn from "../components/GithubSignIn";
import { GithubContext } from '../components/Github/GithubContext';

const Centered = styled('div')({
  display: 'flex',
  justifyContent: 'center',
  flexDirection: 'column'
})

export default function Home() {

  return (
    <div>
      <Head>
        <title>Code Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Centered>
          <h1>Code Review</h1>
          <GithubContext>
            <GithubSignIn />
          </GithubContext>
        </Centered>
      </Container>
    </div>
  )
}
