import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { octokit } from '../lib/octokit';
import { useEffect, useState } from 'react';

import GithubSignIn from "../components/GithubSignIn";
import { GithubContext } from '../components/Github/GithubContext';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Code Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Code Review</h1>
      <GithubContext>
        <GithubSignIn />
      </GithubContext>
    </div>
  )
}
